apiVersion: monitor.nephio.org/v1alpha1
kind: WatcherAgent
metadata:
  name: watcheragent-upf-smf
  namespace: nephio-system
  annotations:
    cloud.nephio.org/cluster: edgecluster-1
spec:
  resyncTimestamp: "2023-05-01T20:48:53Z"
  edgeWatcher:
    addr: 10.244.0.54
    port: "3000"
  watchRequests:
  - group: workload.nephio.org
    version: v1alpha1
    kind: UPFDeployment
    namespace: nephio-system
