apiVersion: monitor.nephio.org/v1alpha1
kind: WatcherAgent
metadata:
  name: watcheragent-upf-smf
  namespace: nephio-system
  annotations:
    cloud.nephio.org/cluster: edgecluster-1
spec:
  resyncTimestamp: "2023-05-22T18:17:08Z"
  edgeWatcher:
    addr: 10.244.0.45
    port: "3000"
  watchRequests:
  - group: workload.nephio.org
    version: v1alpha1
    kind: UPFDeployment
    namespace: nephio-system
  - group: workload.nephio.org
    version: v1alpha1
    kind: SMFDeployment
    namespace: nephio-system
  - group: workload.nephio.org
    version: v1alpha1
    kind: AMFDeployment
    namespace: nephio-system
